config/routes.rb
Clublist::Application.routes.draw do
  resources :payments

  resources :reservations

  resources :tables

  resources :nightclubs
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root "pages#home"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  resources :charges

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  

end

app/views/pages/_show_nightclubs.html.erb
<ul class="card-list">
  <% for nightclub in nightclub %>
  <li class="card">
    <div class="card-inner">
      <%=link_to image_tag(nightclub.image.url (:medium)), nightclub %>
      <h2><%= nightclub.name %></h2>
      <p class="concealed"><%= nightclub.description %></p>

      <%= link_to 'Make a reservation', nightclub, class: "forward reservation highlight" %>
    </div>
  </li>
  <% end %>
</ul>

app/views/pages/_show_payments.html.erb
<div class="titleset all">
  <i class="icon calendar"></i>
  <h3>My Reservations</h3>
</div>

<% a = Payment.find_all_by_user_id(current_user.id) %>

<% if a.size == 0 %>

<p class="align-center">No reservations! We should change that.</p>

<%else%>

<ul>
  <% payment.each do |payment| %>
  <% if payment.user_id == current_user.id %>
  <%if payment.reservation_date >= Date.today.to_s %>
  <% r=payment.table_id %>
  <% n=Table.find(r).nightclub_id %>
  <li>
    <a class="share" href="https://www.facebook.com/share.php?u=socialaxisapp.com" title="Share your reservation on Facebook"><i class="icon facebook"><span>Share</span></i></a>
    <h3><%= Nightclub.find(n).name %> (<%= link_to 'Edit', edit_payment_path(payment) %>)</h3>
    <p><%= payment.reservation_date.strftime("%a %d %b")   %></p>
  </li>
  <%end%>
  <%end%>
  <%end%>
</ul>

<p class="align-center l720"><a href="#" class="forward">Book another table</a></p>
<%end%>

app/views/pages/about.html.erb
<div class="container">
  <div class="group three-four">
    <div>
      <h1>What is Social Axis?</h1>

      <p>Social Axis connects you to the most exclusive nightclubs in your city, while rewarding you for being socially connected.</p>

      <p>We’re currently in Beta testing and would love feedback or partners. <%= link_to "Contact Us", new_contact_path %> - it could be the start of a great friendship.</p>

      <ul class="feature-list">
        <li><i class="icon social big"></i><a href="#how" title="">How does Social Axis work?</a></li>
        <li><i class="icon cocktail big"></i><a href="#hookup" title="">Huh? I can get a hookup? How?</a></li>
        <li><i class="icon lock big"></i><a href="#privacy" title="">Wait?! What can they see?</a></li>
        <li><i class="icon tickets big"></i><a href="#rewards" title="">So I can get into the coolest clubs at a discount?</a></li>
      </ul>

      <p>Social Axis connects you to the most exclusive nightclubs in your city, while rewarding you for being socially connected.</p>

      <h2 id="how">How does Social Axis Work?</h2>
      <p>By giving you control. Social Axis brings all of the best nightclubs in your city together, and lets you book the table you want. We also work with the nigthclubs to get you hookups as often as possible, making it easier for you to party on your terms.</p>

      <h2 id="hookup">Huh? I can get a hookup? How?</h2>
      <p>Simply put, Social Axis leverages your social network to get exclusive hookups from your favorite clubs. Every picture, follower, or check-in gives them exposure and Social Axis rewards you for that.</p>

      <h2 id="privacy">Wait?! What information can they see?</h2>
      <p>Nothing really. Social Axis shares the size of your social influence. Clubs cannot see pictures or status update, but they will know how just how cool you are.</p>

      <h2 id="rewards">So I can get into the coolest clubs at a discount?</h2>
      <p>Not only get. You get in, in style. Sign up Now!</p>
    </div>

    <div class="sidebar">
      <img src="/assets/content/temp1.jpg" alt="Girl in club having a good time" />
      <img src="/assets/content/cute.jpg" alt="Girl in club having a good time" />
      <img src="/assets/content/couple.jpg" alt="Girl in club having a good time" />
    </div>
  </div>
</div>

app/views/pages/carousel.html.erb
<div id="slider" class="slider slick-slider">

  <% Nightclub.connection %>

  <button id="slider-prev" class="slick-prev" type="button"><i class="icon back">&lt;<span></span></i></button>
  <button id="slider-next" class="slick-next" type="button"><i class="icon next">&gt;<span></span></i></button>

  <div><img src="/assets/Rave.jpg" alt="" /></div>
  <div><img src="/assets/tables.jpg" alt="" /></div>
  <div><img src="/assets/club.jpg" alt="" /></div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
 <% if current_user.oauth_token %>
      <% Koala.config.api_version = "v2.1" %>
      <% @graph = Koala::Facebook::API.new(current_user.oauth_token) %>
      <% @a = @graph.get_object("me") %>
      <% friends =  @graph.api("me/friends") %>
      <% permissions = @graph.get_connections('me','permissions') %>

      <div class="overlay"></div>
      <div class="container">

        <div class="group one-three">

          <div class="infobar">

            <div class="profile box">

              <div class="box-inner">

                <div id="profile-slider" class="profile-slider">
                  <div class="profile-details">
                    <img src ="<%= @picture = @graph.get_picture( "me", type: :large) %>" >

                    <dl class="group">
                      <dt>Name:</dt>
                      <dd><%= @a["name"] %></dd>
                      <dt>City:</dt>
                      <% if @a["location"] %>
                        <dd><%= @a["location"]["name"] %></dd>
                      <%else%>
                        <dd>Missing your city</dd>
                      <%end%>
                      <dt class="status-info">Status:</dt>

                      <% if friends["summary"]["total_count"] > 800 and friends["summary"]["total_count"] <= 1000 %>
                        <dd class="status-info"><button id="show-status" class="status">Turned Up</button></dd>
                      
                      <% elsif friends["summary"]["total_count"] >1000 and friends["summary"]["total_count"] <=2000 %>
                        <dd class="status-info"><button id="show-status" class="status">VIP</button></dd>
                      
                      <% elsif friends["summary"]["total_count"] >2000 %>
                        <dd class="status-info"><button id="show-status" class="status">Socialite</button></dd>
                      
                      <%else%>
                        <dd class="status-info"><button id="show-status" class="status">Party Animal</button></dd>
                      
                      <%end%>
                    
                    </dl>
                  </div>

                  <div class="status-details">
                    <button id="close-status" type="button"><i class="icon back"><span></span>Back</i></button>
                       <% if friends["summary"]["total_count"] > 800 and friends["summary"]["total_count"] <= 1000 %>
                        <div class="titleset all">
                          <i class="icon party"></i>
                          <h3>Turned Up</h3>
                        </div>
                        <p>Your response to 'Turn Down for What' is popping another champagne bottle. You may need advil and sunglasses regularily during brunch on the weekends, but you always have a good story. Hopefully the Social Axis hookups are giving you reasons to Turn Up more often as well. </p>

                      <% elsif friends["summary"]["total_count"] >1000 and friends["summary"]["total_count"] <=2000 %>

                        <div class="titleset all">
                          <i class="icon party"></i>
                          <h3>VIP</h3>
                        </div>
                        <p>People are really starting to know your name around the city, and your friends are starting to look at you as the token 'Wild Friend'. It doesn't matter though, I bet they all ask you to book the tables. We'll keep your nice Social Axis hookups between us though. </p>

                       <% elsif friends["summary"]["total_count"] >2000 %>

                        <div class="titleset all">
                          <i class="icon party"></i>
                          <h3>Socialite</h3>
                        </div>
                        <p>Everyone in the venue can instantly see that you run this place. You feel at home out and underneath the flashing lights. In fact, we'd go as far to say you make partying look easy. Hopefully your Social Axis hookups make it easier on your bank account as well.</p>

                      <%else%>

                        <div class="titleset all">
                          <i class="icon party"></i>
                          <h3>Party Animal</h3>
                        </div>
                        <p>You definitely know how to go out and have a fun time. Now all you need to do is channel your inner spirit animal and book some tables. Not only will your friends be happy you're treating them to a good time, but you just might see some extra Social Axis hookups. </p>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>

            <div class="reservation-list box">
              <div class="box-inner">
                <%= render :partial=>'show_payments', :locals=> {:reservation => Reservation.find(:all),:table =>Table.find(:all), :nightclub => Nightclub.find(:all), :payment => Payment.find(:all)} %>
              </div>
            </div>
          </div>

          <% if @a["location"]["name"] == "New York, New York" %>
            <div>
              <%= render :partial=>'show_nightclubs', :locals=> {:nightclub => Nightclub.find(:all)} %>
            </div>
          <%else%>
        
                  <div>
                    <p class="warning">Sorry! Social Axis isn't currently in your city. We’re currently piloting in NYC, but if you're interested in Social Axis coming to your city, <%= link_to "Contact Us", new_contact_path %> - it could be the start of a great friendship. However, feel free to check out our NYC clubs below: </p>
                    <%= render :partial=>'show_nightclubs', :locals=> {:nightclub => Nightclub.find(:all)} %>
                  </div>
            <%end%>

        </div>
      </div>

      <% end %>


    <% else %>

      <div class="container">

        <div id="carousel" class="slick-slider carousel">

          <button id="carousel-prev" class="slick-prev" type="button"><i class="icon back">&lt;<span></span></i></button>
          <button id="carousel-next" class="slick-next" type="button"><i class="icon next">&gt;<span></span></i></button>

          <div>
            <div class="inner">
              <img src="/assets/content/lady.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/DJ.jpg" alt="Girl in club having a good time"/>
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/bartender.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/champagne.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/temp1.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/crowd.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/cute.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
          <div>
            <div class="inner">
              <img src="/assets/content/couple.jpg" alt="Girl in club having a good time" width="320" height="320" />
            </div>
          </div>
        </div>

        <div class="features">
          <h2>Take Control<br class="l490" /> of your Night</h2>

          <div>
            <img src="/assets/icons/social.png" alt="A loop with circles around it, making up a network" width="126" height="140" />
            <h3>Access</h3>
            <p>Social Axis leverages your social network to get exclusive access to your favorite nightlife.</p>
            <a class="forward" href="/about/" title="Learn more about Hookups">Learn more</a>
          </div>

          <div class="middle">
            <img src="/assets/icons/cocktail.png" alt="A cocktail in a glass with a slice of fruit on the lip" width="143" height="140" />
            <h3>Book Your Table</h3>
            <p>Social Axis brings all of the best nightclubs in your city together, and lets you book the table you want.</p>
            <a class="forward" href="/about/" title="Learn more about Booking a Table">Learn more</a>
          </div>

          <div>
            <img src="/assets/icons/tickets.png" alt="A pair of tickets" width="142" height="140" />
            <h3>Get Comped</h3>
            <p>Every picture, follower, or check-in gives nightclubs exposure and Social Axis comps you for that.</p>
            <a class="forward" href="/about/" title="Learn more about Rewards">Learn more</a>
          </div>
        </div>

      </div>


    <% end %>

app/views/pages/privacy.html.erb
<div class="container">
  <div class="group three-four">
<h1>Privacy Policy</h1>

<h4>Last Updated: July 1, 2014</h4>

This Privacy Policy explains how information about you is collected, used and disclosed by Social Axis, LLC. and our subsidiaries (collectively, "Social Axis") when you use our websites, mobile websites, mobile applications and other online products and services (collectively, the "Services") or when you otherwise interact with us.

We may change this Privacy Policy from time to time. If we make changes, we will notify you by revising the date at the top of the policy and, in some cases, we may provide you with additional notice (such as adding a statement to our websites' homepages or sending you a notification). We encourage you to review the Privacy Policy whenever you access the Services to stay informed about our information practices and the ways you can help protect your privacy.

<h3>Collection of Information</h3>

<h4>Information You Provide to Us</h4>

We collect information you provide directly to us, and through the allowed permissions on facebook. For example, we collect your email, location, name, and friend count through the facebook login, and use this information for calculating "hookups" on Social Axis. In addition reservation count and infortmation are also stored to be used to show your social value to clubs. The actually reservation information is never shared, just used to calculate your status. 

<h4>Information We Collect Automatically When You Use the Services</h4>

When you access or use our Services, we automatically collect information about you, including:

Reservation Information: When you make a reservation via our Services, we collect information about the reservation, including the time, date, party size, hookup amount, nightclub,what table and cost. 

Log Information: We log information about your use of our websites, including your browser type and language, access times, pages viewed, your IP address and the website you visited before navigating to our websites.

We may also obtain information from other sources and combine that with information we collect through our Services.

<h3>Use of Information</h3>

We may use information about you for various purposes, including to:

Provide, maintain and improve our Services, including to provide additional features and content for your messages;
Provide and deliver the products and services you request, process transactions and send you related information;
Respond to your comments, questions and requests and provide customer service;
Send you technical notices, updates, security alerts and support and administrative messages;
Communicate with you about products, services, offers, promotions, rewards, and events offered by Social Axis and others, and provide news and information we think will be of interest to you;
Monitor and analyze trends, usage and activities in connection with our Services;
Personalize and improve the Services and provide advertisements, content or features that match user profiles or interests;
Link or combine with information we get from others to help understand your needs and provide you with better service;
Detect, investigate and/or prevent fraudulent, unauthorized or illegal activity; and
Carry out any other purpose for which the information was collected.
Social Axis is based in the United States and the information we collect is governed by U.S. law. By accessing or using the Services or otherwise providing information to us, you consent to the processing and transfer of information in and to the U.S. and other countries.

<h3> Sharing of Information </h3>

We do not share any of your information with any outside party. The information is only used to calculate your status, which is used to determine "hookup" value.


<h3> Security </h3>

We take reasonable measures to help protect information about you from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction.


Contact

To contact us, please write to get.social.axis@gmail.com

</div>
</div>