config/routes.rb
Clublist::Application.routes.draw do
  resources :payments

  resources :reservations

  resources :tables

  resources :nightclubs
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root "pages#home"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  resources :charges

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :set_table, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  #def edit
  #end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(table_params)

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render action: 'show', status: :created, location: @table }
      else
        format.html { render action: 'new' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    respond_to do |format|
      if @table.update(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table
      @table = Table.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def table_params
      params.require(:table).permit(:nightclub_id, :min_cost, :image, :description, :location)
    end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_carousel.html.erb
<div id="slider" class="slider slick-slider">

  <% Nightclub.connection %>

  <button id="slider-prev" class="slick-prev" type="button"><i class="icon back">&lt;<span></span></i></button>
  <button id="slider-next" class="slick-next" type="button"><i class="icon next">&gt;<span></span></i></button>

  <div><img src="/assets/content/temp2.jpg" alt="" /></div>
  <div><img src="/assets/content/temp2.jpg" alt="" /></div>
  <div><img src="/assets/content/temp2.jpg" alt="" /></div>
</div>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="errors" class="message error">
      <%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nightclub_id %><br>
    <%= f.number_field :nightclub_id %>
  </div>
  <div class="field">
    <%= f.label :min_cost %><br>
    <%= f.number_field :min_cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

 <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>

   <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/_new_payment.html.erb
<%= form_for(payment) do |f| %>
  <% if payment.errors.any? %>
    <div id="errors" class="message error">
      <%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

  <%- if @cc_last_4 %>
    <div class="field">
      <input type="radio" name="saved_card" value="true"/> Saved Card
      <input type="radio" name="saved_card" value="false"/> New Card
    </div>

    <div id="saved_card">
      <div class="field">
        <label>Saved Card</label>
        <input id="saved-number" type="text" disabled="true" value="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; <%= @cc_last_4 %>" />
      </div>
    </div>
  <%- end %>
  <div id="new_card">
    <div class="field">
      <%= f.hidden_field :stripe_token %>
    </div>


   <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :table_id %><br>
    <%= f.number_field :table_id %>
  </div>
  <div class="field">
    <%= f.label :females %><br>
    <%= f.number_field :females %>
  </div>

  <div class="field">
    <%= f.label :males %><br>
    <%= f.number_field :males %>
  </div>


    <div class="field">
      <label>Card Number</label>
      <input id="card-number" type="text" placeholder="4242 4242 4242 4242" />
    </div>
    <div class="field">
      <label>CV Code</label>
      <input id="cvc" type="text" placeholder="123" />
    </div>
    <div class="field">
      <label>Expiry Month</label>
      <input id="exp-month" type="text" placeholder="12" />
    </div>
    <div class="field">
      <label>Expiry Year</label>
      <input id="exp-year" type="text" placeholder="14" />
    </div>
  </div>

<div class="field">
     <%= f.hidden_field :reservation_date %>
  </div>

   <div class="field">
     <%= f.hidden_field :males %>
  </div>

   <div class="field">
     <%= f.hidden_field :females %>
  </div>

  <div class="field">
     <%= f.hidden_field :amount %>
  </div>

    <div class="field">
     <%= f.hidden_field :table_id %>
  </div>

 <div class="field">
     <%= f.hidden_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/_new_reservation.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="errors" class="message error">
      <%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  <% end %>

<form role="form">

  <fieldset class="suffixed-labels">
    <%= f.label :reservation_date , "When are you looking to party:" %>

    <div class="inputset">
      <%= f.date_field :reservation_date, class: "form-control" %>
      <button id="datepicker-button" class="date-picker">Choose date</button>
    </div>
  </fieldset>

  <fieldset class="suffixed-labels" name="no-of-people" data-error-msg="At least one person must be going to your party">

    <%= f.label :females , "How many people will be going to your party:" %>
    <div class="inputset">
      <%= f.number_field :females,  class: "form-control" %>
      <span class="suffix"><i class="icon girl black"></i><span>Women</span></span>
    </div>

    <div class="inputset">
      <%= f.number_field :males, class: "form-control"  %>
      <span class="suffix"><i class="icon boy black" ></i><span>Men</span></span>
    </div>

  </fieldset>

   <div class="field">
     <%= f.hidden_field :amount %>
  </div>

   <div class="field">
     <%= f.hidden_field :user_id %>
  </div>

   <div class="field">
     <%= f.hidden_field :table_id %>
  </div>

  <div class="field">
     <%= f.hidden_field :nightclub_id %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary btn-block" %>
  </div>
</form>
<% end %>

app/views/tables/_show_tables.html.erb
<table>
  <thead>
    <tr>
      <td class="number">#</td>
      <td class="location">Location</td>
      <td class="min">Table Min.</td>
      <td class="reserve"></td>
    </tr>
  </thead>

  <%a = 1 %>
  <tbody>
    <% tables.each do |table| %>
    <tr>
      <td class="number"><%= a %></td>
      <td class="location"><%= table.location %></td>
      <td class="min">$<%= table.min_cost %></td>
      <td class="reserve">
        <input type="radio" name="location" value="<%= a %>" required />

        <!--%= link_to 'Make a reservation', table %></td-->

        <button type="button"><i class="icon cocktail blue"></i><span><%=link_to 'Book my table', table%> </span></button>
        </td>
    </tr>
      <%a = a+ 1 %>
    <% end %>
  </tbody>
</table>

app/views/tables/edit.html.erb
<!--h1>Editing table</h1-->

<%#= render 'form' %>

<%#=link_to 'Show', @table %> |
<%#= link_to 'Back', tables_path %>


<div class="jumbotron center">
	<h2> Go  <%= link_to "home", root_path %> <%=current_user.name%> you're drunk! </h2>



</div>
</br>
</br>
</br>

app/views/tables/index.html.erb
<div class="container">
  <div class="group card">
    <div class="card-inner">
      <h1>Listing tables</h1>

      <table>
        <thead>
          <tr>
             <div class="table">
            <th>Nightclub</th>
            <th>Min cost</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @tables.each do |table| %>
            <tr>
              <td><%= table.nightclub_id %></td>
              <td><%= table.min_cost %></td>
              <td><%= link_to 'Show', table %></td>
              <td><%= link_to 'Edit', edit_table_path(table) %></td>
              <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>


      <%= link_to 'New Table', new_table_path %>
    </div>
  </div>

</div>

app/views/tables/new.html.erb
<div class="container">
	<h2 class="align-center"> Go  <%= link_to "home", root_path %> <%=current_user.name%> you're drunk! </h2>

<div class="card">
	<div class="card-inner">
		<h1>Add a Table</h1>
		<%= render 'form' %>
	</div>
</div>

<%= link_to 'Back', tables_path %>

</div>

app/views/tables/show.html.erb
<div class="container">
  <div class="group two-three">
    <div class="card club">
      <div class="card-inner">

        <%= render :partial=>'carousel' %>

        <div class="mobile-details">
          <% Nightclub.connection %>
          <h1><%=Nightclub.find(@table.nightclub_id).name%></h1>

          <ul class="contact-details">
            <li class="phone"><i class="icon phone black"></i><%= Nightclub.find(@table.nightclub_id).phone_number %></li>
            <li class="marker"><i class="icon marker black"></i><%= Nightclub.find(@table.nightclub_id).address %></li>
          </ul>

          <div class="concealed description">
            <p><%= Nightclub.find(@table.nightclub_id).description %></p>
          </div>

          <div class="titleset">
            <i class="icon cocktail black"></i>
            <h2>Book Table</h2>
          </div>
        </div>

          <%# Partial for making reservation %>
          <%= render :partial=>'new_reservation', :locals=> {:reservation => Reservation.new(:table_id=> @table.id, :amount=> @table.min_cost, :nightclub_id=> @table.nightclub_id) } %>
      </div>
    </div>

    <div class="infobar box">

      <div class="box-inner">

        <div class="headerset">
          <h1><%= Nightclub.find(@table.nightclub_id).name %></h1>

          <ul class="contact-details">
            <li class="phone"><i class="icon phone"></i><%= Nightclub.find(@table.nightclub_id).phone_number %></li>
            <li class="marker"><i class="icon marker"></i><%= Nightclub.find(@table.nightclub_id).address %></li>
          </ul>
        </div>

        <p><%= Nightclub.find(@table.nightclub_id).description %></p>
      </div>
    </div>

  </div>
</div>