config/routes.rb
Clublist::Application.routes.draw do
  resources :payments

  resources :reservations

  resources :tables

  resources :nightclubs
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root "pages#home"
  get "about" => "pages#about"
  get "privacy" => "pages#privacy"
  resources :charges

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]
  

end

app/views/layouts/_footer.html.erb
</div>

<div class="cta">
  <div class="container">
    <% if !user_signed_in? %>
      <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "button facebook" %>
      <p class="hint">...and get instant access</p>
    <% else %>

      <%
        # Only show the "Find your table" button when signed in and when not already on the booking page

        currentUri = request.env['PATH_INFO']

        # Get the directory name by removing the first / then get the text before the second /
        cleanDirName = currentUri[1..-1].split("/").first

        if user_signed_in? and cleanDirName != nil and cleanDirName != "nightclubs"
      %>

      <a href="/" class="button"><i class="icon cocktail"><span></span></i>Find Your Table</a>
      <p class="hint">Make a reservation and party on your terms</p>
      <% end %>
    <% end %>

  </div>

  <div class="overlay"></div>
</div>

</main>

<footer class="container" role="contentinfo">

<ul class="social-links">
  <li><a href="#" title="View Social Axis on Twitter"><i class="icon twitter">Twitter<span></span></i></a></li>
  <li><a class="icon instagram" href="#" title="View Social Axis on Instagram"><i class="icon instagram">Instagram<span></span></i></a></li>
  <li><a class="icon facebook" href="#" title="View Social Axis on Facebook"><i class="icon facebook">Facebook<span></span></i></a></li>
</ul>

<nav role="navigation">
  <ul>
    <!-- # If current page, add "current" class to link -->

    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact Us", new_contact_path %></li>
    <% if user_signed_in? %>

        <li class="l720"><%= link_to "Profile", root_path %></li>
        <li><%= link_to "Book a table", root_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path %></li>
      <% else %>
        <li><%= link_to "Sign in", user_omniauth_authorize_path(:facebook) %></li>
      <% end %>
  </ul>
</nav>

<%= link_to image_tag('/assets/social-axis-logo.png'), root_path , id: "logo", class: "logo" %>

<small>Copyright &copy; <time datetime="2014">2014</time> <%= link_to "Social Axis", root_path %></small>
</footer>

app/views/layouts/_header.html.erb
<%

currentUri = request.env['PATH_INFO']

# Get the directory name by removing the first / then get the text before the second /
cleanDirName = currentUri[1..-1].split("/").first

# Change the <body> class per page
case cleanDirName

when nil, ""
    if user_signed_in?
      section = "club"
    else
      section = "front"
    end

  when "nightclubs", "tables", "payments"
    section = "club"

  when "reservations"
    section = "reservations"

  when "about", "contacts"
    section = "single"

  else
    section = ""
end

## Add a class of "interior" when viewing pages that can only be accessed when signed in
case section

when "club", "reservations", "tables", "payments"
    section += " interior"
end

%>

<body class="<% concat section %>">
  <% if section == "club interior" or section == "reservations interior" %>
  <div class="overlay"></div>
  <% end %>

  <header role="banner">
    <% if section == nil or "" %>
    <div class="header-bg"></div>
    <% end %>
    <div class="overlay"></div>
    <nav role="navigation">
      <div class="group container">
        <%= link_to image_tag('/assets/social-axis-logo.png'), root_path , id: "logo", class: "logo" %>
        <a href="#links" class="menu" id="menu">Menu</a>
        <div id="links">
          <button id="close-menu" type="button"><i class="icon close">Close<span></span></i></button>
          <ul>

            <!-- # If current page, add "current" class to link -->

            <li><%= link_to "About", about_path, class: "current" %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            <% if user_signed_in? %>

                <li class="l720"><%= link_to "Profile", root_path %></li>
                <li><%= link_to "Book a table", root_path, class: "boxed" %></li>
                <li class="l720"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", user_omniauth_authorize_path(:facebook), class: "boxed" %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>

  <% currentUri = request.env['PATH_INFO'] %>
  <% if cleanDirName == nil or cleanDirName == "" and !user_signed_in? %>
    <div class="feature-wrapper">
      <div class="feature">
        <h1 class="title">Connect with the<br class="l450" /> Hottest Nightlife<br class="l450" /> in your Area</h1>
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), class: "button facebook" %>
        <p class="hint">Sign in with facebook <br class="l450" />to receive exclusive access<br class="l450" /> based on your social network</p>
      </div>
    </div>
  <% end %>

  </header>

  <% if section == "single" %>
  <div class="banner">
    <div class="overlay"></div>
  </div>
  <% end %>

  <main id="main" role="main">

    <div class="wrapper">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta name="description" content="">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">


  <title>Social Axis</title>

  <%= favicon_link_tag '/assets/favicon.ico' %>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!--[if lt IE 10]>
    <link href="/assets/ie/ie.css" rel="stylesheet">
  <![endif]-->
  <!--[if IE 7]>
    <link href="/assets/ie/ie7.css" rel="stylesheet">
  <![endif]-->

    <%= javascript_include_tag "jquery", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "third-party/modernizr.min.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "jquery_ujs", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "jquery.turbolinks", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "payments", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "http://stripe.github.io/jquery.payment/lib/jquery.payment.js" %>
  <%= javascript_tag "Stripe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';" %>
	<%= csrf_meta_tags %>

  <meta property="og:site_name" content="Social Axis" />
  <meta property="og:title" content="Just booked a table with Social Axis" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:description" content="Just booked a table with Social Axis" />
  <meta property="og:image" content="Link to an image here" />


  <!--[if lt IE 9]>
    <script src="/assets/javascripts/html5shiv-printshiv.min.js"></script>
    <script src="/assets/javascripts/nwmatcher-1.2.5-min.js"></script>
    <script src="/assets/javascripts/selectivizr-min.js"></script>
    <script src="/assets/javascripts/respond.min.js"></script>
  <![endif]-->
</head>
<body>
      <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '568229366629074',
          xfbml      : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

<%= render 'layouts/header' %>

 <% flash.each do |name, msg| %>
      <%#= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
<%= yield %>

<%= render 'layouts/footer' %>
<%= javascript_include_tag "third-party.min.js", "data-turbolinks-track" => true %>
<%= javascript_include_tag "scripts.js", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/profile.html.erb
<% if user_signed_in? %>
<% if current_user.oauth_token %>
			<% @graph = Koala::Facebook::API.new(current_user.oauth_token) %>
			<% @a = @graph.get_object("me") %>
			<%# @friends = @graph.get_connections("me", "friends") %>

			<div class="overlay"></div>
			<div class="container">
				<div class="group">

					<div class="profile box">

						<div class="box-inner">

							<div id="profile-slider" class="profile-slider">
								<div class="profile-details">
									<img src ="<%= @picture = @graph.get_picture( "me", type: :large) %>" >

									<dl class="group">
										<dt>Name:</dt>
										<dd><%= @a["name"] %></dd>

										<% b = 0 %>
										<%# @friends.each do |f| %>
										<% b = b+1 %>
										<%# end %>

										<dt>City:</dt>
										<% if @a["location"] %>
											<dd><%= @a["location"]["name"] %></dd>
										<%else%>
											<dd>New York, NY</dd>
										<%end%>
										<dt class="status-info">Status:</dt>

										<%# if @friends.size > 800 and @friends.size <= 1200 %>
											<dd class="status-info"><button id="show-status" class="status">Turned Up</button></dd>
										<%# elsif @friends.size >1200 and @friends.size <=2000 %>
											<!-- <dd class="status-info"><button id="show-status" class="status">VIP</button></dd> -->
										<%# elsif @friends.size >2000 %>
											<!-- <dd class="status-info"><button id="show-status" class="status">Socialite</button></dd> -->
										<%#else%>
											<!-- <dd class="status-info"><button id="show-status" class="status">Party Animal</button></dd> -->
										<%#end%>
									</dl>
								</div>

								<div class="status-details">
									<button id="close-status" type="button"><i class="icon back"><span></span>Back</i></button>
										<%# if @friends.size > 800 and @friends.size <= 1200 %>

										<div class="titleset all">
											<i class="icon party"></i>
											<h3>Turned Up</h3>
										</div>
										<p>Turned up description</p>

										<%# elsif @friends.size >1200 and @friends.size <=2000 %>

										<!-- <div class="titleset all">
											<i class="icon party"></i>
											<h3>VIP</h3>
										</div>
										<p>VIP description</p> -->

										<%# elsif @friends.size >2000 %>

										<!-- <div class="titleset all">
											<i class="icon party"></i>
											<h3>Socialite</h3>
										</div>
										<p>Socialite description</p> -->

										<%#else%>

									<!-- <div class="titleset all">
										<i class="icon party"></i>
										<h3>Party Animal</h3>
									</div>
									<p>Party animal description</p> -->
									<%#end%>
								</div>
							</div>
						</div>
					</div>

					<div class="reservation-list box">
						<div class="box-inner">
							<%= render :partial=>'show_payments', :locals=> {:reservation => Reservation.find(:all),:table =>Table.find(:all), :nightclub => Nightclub.find(:all), :payment => Payment.find(:all)} %>
						</div>
					</div>
				</div>
			</div>

<% end %>
<% end %>